# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "ehci_pci" "ahci" "xhci_pci" "firewire_ohci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  boot.loader.grub = {
  	device = "/dev/osdisk";
	enable = true;
	useOSProber = true;
	version = 2;
  };

  nixpkgs.config.allowUnfree = true;

  #services.xserver.displayManager.gdm.wayland = false;

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/f82ba771-1f52-43cb-9091-a1589c1b7212";
      fsType = "f2fs";
    };

  boot.initrd.luks.devices."luks-b3af58fe-579b-41a6-b1f9-af17408b1144".device = "/dev/disk/by-uuid/b3af58fe-579b-41a6-b1f9-af17408b1144";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/ef1dabc1-5450-4498-94b0-4dd2f621475d";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/90aaf398-b7a3-441d-887a-52b81057053a";
	encrypted = {
		enable = true;
		keyFile = "/mnt-root/root/swap.key";
		label = "luksswap";
		blkDev = "/dev/disk/by-uuid/69a7fdaf-c760-4870-bbd2-cf6592751c0e";
	};
	}
    ];

  # high-resolution display
  services.udev.extraRules = ''
    SUBSYSTEM=="block", ENV{DEVTYPE}=="disk", ENV{ID_SERIAL}=="CT500MX500SSD1_2113E5911C84", SYMLINK+="osdisk"
  '';

  services.xserver.videoDrivers = [ "nvidia" ];
  #hardware.nvidia.package = config.boot.kernelPackages.nvidiaPackages.legacy_390;

  hardware.video.hidpi.enable = lib.mkDefault true;
}
