#! /bin/bash
# toggleTouchpad by Brendon Dugan
# Toggles a touchpad on or off depending on it's current state or CLI argument
#
# To configure, run the command 'xinput list' in terminal and identify your
# touch pad.
# Using the output of the above command, change the touchpadString variable
# to a substring of your touchpad's description that is unique to that device.
#
# To run, simply type 'toggleTouchpad' to toggle your touchpad on or off, or
# 'toggleTouchpad on' to explicitly turn your touchpad on, or
# 'toggleTouchpad off' to explicitly turn it off.
#
# Enjoy!
touchpadString="touch"
touchpadID=$(xinput --list | grep xwayland-touch | grep -o id=.. | cut -d'=' -f2)
touchpadEnabled=$(xinput list-props $touchpadID | grep "Device Enabled" | awk -F ":" '{print $2}')

# Check for arguments on the command line
if [ $# -eq 1 ]; then               # Any arguments?
    arg1=$(echo $1 | tr [:upper:] [:lower:])    # Yes, convert to lower case
    cliArg=1                    # Set flag that we have one
else                        # There is no argument.
    cliArg=0                    # Clear flag
fi

if [ $cliArg -eq 1 ]; then          # Did we get an argument?
    if [ $arg1 = 'on' ]; then           # Yes, was it "on"?
    xinput --set-prop $touchpadID "Device Enabled" 1
                        # Yes, enable the touchpad
    elif [ $arg1 = 'off' ]; then        # No, was it "off"?
    xinput --set-prop $touchpadID "Device Enabled" 0
                        # Yes, disable the touchpad
    else                    # None of the above, so...
    sleep 1                 # ...sleep one second, exit
    fi

else                        # No argument, toggle state
    if [ $touchpadEnabled -eq 1 ]; then     # Enabled now?
        xinput --set-prop $touchpadID "Device Enabled" 0
        unclutter -idle 0 &
                        # Yes, so disable it
    else                    # Must be disabled, so...
        xinput --set-prop $touchpadID "Device Enabled" 1
        killall unclutter
                        # ...enable it
    fi
fi
