# This file has been generated by node2nix 1.6.0. Do not edit!

{ nodeEnv, fetchurl, fetchgit, globalBuildInputs ? [ ] }:

let
  sources = {
    "minimist-1.2.0" = {
      name = "minimist";
      packageName = "minimist";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-1.2.0.tgz";
        sha1 = "a35008b20f41383eec1fb914f4cd5df79a264284";
      };
    };
    "printf-0.1.3" = {
      name = "printf";
      packageName = "printf";
      version = "0.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/printf/-/printf-0.1.3.tgz";
        sha1 = "27e935bae4f55db1fdc18368689e9561ce551226";
      };
    };
  };
in {
  "bars-jez/bars#6f5cde29afce17dbf6b28e9b33f7c8e8c28166f9" =
    nodeEnv.buildNodePackage {
      name = "bars";
      packageName = "bars";
      version = "1.2.2";
      src = fetchgit {
        url = "git://github.com/jez/bars";
        rev = "6f5cde29afce17dbf6b28e9b33f7c8e8c28166f9";
        sha256 =
          "697aee1dad00ce4db55115661d469c19ac36c948811394bebd06ae650d8b1488";
      };
      dependencies = [ sources."minimist-1.2.0" sources."printf-0.1.3" ];
      buildInputs = globalBuildInputs;
      meta = {
        description = "Ascii bar charting";
        license = "MIT";
      };
      production = true;
      bypassCache = true;
    };
}
